# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: uncefact
baseurl: "/uncefact" # the subpath of your site, e.g. /blog

markdown: kramdown
kramwdown:
  parse_block_html: true

gems: [jekyll-toc]

collections:
  vocabulary:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "vocabulary"
    values:
      layout: "vocabulary"

exclude:
  - .idea
  - .git
  - pages
  - specs
  - docs
